ROBOT_VARS = {
    "timestamp": "DOUBLE",
    "target_q": "VECTOR6D",
    "target_qd": "VECTOR6D",
    "target_qdd": "VECTOR6D",
    "target_current": "VECTOR6D",
    "target_moment": "VECTOR6D",
    "actual_q": "VECTOR6D",
    "actual_qd": "VECTOR6D",
    "actual_current": "VECTOR6D",
    "joint_control_output": "VECTOR6D",
    "actual_TCP_pose": "VECTOR6D",
    "actual_TCP_speed": "VECTOR6D",
    "actual_TCP_force": "VECTOR6D",
    "target_TCP_pose": "VECTOR6D",
    "target_TCP_speed": "VECTOR6D",
    "joint_temperatures": "VECTOR6D",
    "actual_execution_time": "DOUBLE",
    "robot_mode": "INT32",
    "joint_mode": "VECTOR6INT32",
    "safety_mode": "INT32",
    "actual_tool_accelerometer": "VECTOR3D",
    "speed_scaling": "DOUBLE",
    "target_speed_fraction": "DOUBLE",
    "actual_momentum": "DOUBLE",
    "actual_main_voltage": "DOUBLE",
    "actual_robot_voltage": "DOUBLE",
    "actual_robot_current": "DOUBLE",
    "actual_joint_voltage": "VECTOR6D",
    "runtime_state": "UINT32",
    "elbow_position": "VECTOR3D",
    "elbow_velocity": "VECTOR3D",
    "robot_status_bits": "UINT32",
    "safety_status_bits": "UINT32",
    "payload": "DOUBLE",
    "payload_cog": "VECTOR3D"
    # "payload_inertia": "VECTOR6D" # 3.15
    # "script_control_line": "UINT32" # 3.14
    # "ft_raw_wrench": "VECTOR6D" # 5.9.0
}

IO_VARS = {
    "actual_digital_input_bits": "UINT64",
    "actual_digital_output_bits": "UINT64",
    "analog_io_types": "UINT32",
    "standard_analog_input0": "DOUBLE",
    "standard_analog_input1": "DOUBLE",
    "standard_analog_output0": "DOUBLE",
    "standard_analog_output1": "DOUBLE",
    "io_current": "DOUBLE",
    "euromap67_input_bits": "UINT32",
    "euromap67_output_bits": "UINT32",
    "euromap67_24V_voltage": "DOUBLE",
    "euromap67_24V_current": "DOUBLE",
    "tool_mode": "UINT32",
    "tool_analog_input_types": "UINT32",
    "tool_analog_input0": "DOUBLE",
    "tool_analog_input1": "DOUBLE",
    "tool_output_voltage": "INT32",
    "tool_temperature": "DOUBLE",
    "tcp_force_scalar": "DOUBLE",
    "tool_output_mode": "UINT8",
    "tool_digital_output0_mode": "UINT8",
    "tool_digital_output1_mode": "UINT8"
}

REGISTER_VARS = {
    "output_bit_registers0_to_31": "UINT32",
    "output_bit_registers32_to_63": "UINT32",
    "output_int_register_0": "INT32",
    "output_int_register_1": "INT32",
    "output_int_register_2": "INT32",
    "output_int_register_3": "INT32",
    "output_int_register_4": "INT32",
    "output_int_register_5": "INT32",
    "output_int_register_6": "INT32",
    "output_int_register_7": "INT32",
    "output_int_register_8": "INT32",
    "output_int_register_9": "INT32",
    "output_int_register_10": "INT32",
    "output_int_register_11": "INT32",
    "output_int_register_12": "INT32",
    "output_int_register_13": "INT32",
    "output_int_register_14": "INT32",
    "output_int_register_15": "INT32",
    "output_int_register_16": "INT32",
    "output_int_register_17": "INT32",
    "output_int_register_18": "INT32",
    "output_int_register_19": "INT32",
    "output_int_register_20": "INT32",
    "output_int_register_21": "INT32",
    "output_int_register_22": "INT32",
    "output_int_register_23": "INT32",
    "output_double_register_0": "DOUBLE",
    "output_double_register_1": "DOUBLE",
    "output_double_register_2": "DOUBLE",
    "output_double_register_3": "DOUBLE",
    "output_double_register_4": "DOUBLE",
    "output_double_register_5": "DOUBLE",
    "output_double_register_6": "DOUBLE",
    "output_double_register_7": "DOUBLE",
    "output_double_register_8": "DOUBLE",
    "output_double_register_9": "DOUBLE",
    "output_double_register_10": "DOUBLE",
    "output_double_register_11": "DOUBLE",
    "output_double_register_12": "DOUBLE",
    "output_double_register_13": "DOUBLE",
    "output_double_register_14": "DOUBLE",
    "output_double_register_15": "DOUBLE",
    "output_double_register_16": "DOUBLE",
    "output_double_register_17": "DOUBLE",
    "output_double_register_18": "DOUBLE",
    "output_double_register_19": "DOUBLE",
    "output_double_register_20": "DOUBLE",
    "output_double_register_21": "DOUBLE",
    "output_double_register_22": "DOUBLE",
    "output_double_register_23": "DOUBLE"
}
